name: Update GPT-Herzwerk via External Feed

on:
  schedule:
    - cron: '0 18 * * *'  # täglich um 18 Uhr
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch new GPT content
        run: |
          mkdir -p data
          curl -L -s https://gpt-live-feed.s3.eu-central-1.amazonaws.com/daily.json
      - name: Commit & push
        run: |
          git config user.name "mmessa28"
          git config user.email "marcomessa02@gmail.com"
          git add data/daily.json
          git commit -m "Auto-update from external GPT feed 🤖" || echo "No changes"
          git push
